---
apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{  .Values.service.protocol }}
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
  name: {{ .Chart.Name }}-studio
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Chart.Name }}-studio
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortStudio }}
      protocol: {{  .Values.service.protocol }}
  selector:
    app: {{ .Chart.Name }}